name: Publish release notes to docs.

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  test-release-notes:
    name: Test release notes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
      - name: Print release notes
        run: |
          echo "Release notes: ${{ github.event.release.body }}"