name: Publish release notes to docs.

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  test-release-notes:
    name: Test release notes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          path: 'source'
          fetch-depth: 0
          fetch-tags: true
      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          repository: 'Openlineage/openlineage-site'
          path: 'target'
      # Print debug content of release notes from webhook
      - name: Print release notes
        run: |
          echo "Release notes: ${{ github.event.release.body }}"
